In [0]:
import numpy as np

In [3]:
#array creation

array2 = np.array([1, 2])
print("Array2 = " + str(array2))
print("Array2 shape " + str(array2.shape))
print(type(array2))
print('\n')

array3 = np.array([[1, 2], [3, 4]])
print("Array3 = " + str(array3))
print("Array4 shape: " + str(array3.shape))
print('\n')

array4 = np.array([[1, 2]])
print("Array4 = " + str(array4))
print("Array4 shape: " + str(array4.shape))

Array2 = [1 2]
Array2 shape (2,)
<class 'numpy.ndarray'>


Array3 = [[1 2]
 [3 4]]
Array4 shape: (2, 2)


Array4 = [[1 2]]
Array4 shape: (1, 2)


In [0]:
#Reshaping Arrays
#arr.reshape(shape)

array5 = array3.reshape((4, 1))
print("Array5 :\n" + str(array5), "\n\nArray3: \n" + str(array3))

#arr.resize(shape)
array3.resize((1, 4))
print("\nArray3 : \n" + str(array3))

Array5 :
[[1]
 [2]
 [3]
 [4]] 

Array3: 
[[1 2]
 [3 4]]

Array3 : 
[[1 2 3 4]]


In [0]:
#Special Array Initialization

#fill with zeros
zero_array = np.zeros((5, 5))
print("Zeros array:\n" + str(zero_array))

#fill with ones
ones_array = np.ones((5, 5))
print("\nOnes array:\n" + str(ones_array))

#fill with certain value
array3 = np.full((5, 5), 420)
print("\nCertain Valued Array:\n" + str(array3))

#identity array
id_arr = np.eye(5, 5)
print("\nIdentity Array:\n" + str(id_arr))

#random valued arrays [0,1)

rand_arr1 = np.random.rand(5, 5)
print("\nRandomized Array:\n"+str(rand_arr1))

#distributed standart normal deviation
rand_arr2 = np.random.randn(5, 5)
print("\nRandomized Array2:\n" + str(rand_arr2))

Zeros array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Ones array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Certain Valued Array:
[[420 420 420 420 420]
 [420 420 420 420 420]
 [420 420 420 420 420]
 [420 420 420 420 420]
 [420 420 420 420 420]]

Identity Array:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Randomized Array:
[[0.36167077 0.11832052 0.55417038 0.02104903 0.91846544]
 [0.97728565 0.39926083 0.50501568 0.59746547 0.51384948]
 [0.87186858 0.99529919 0.51730905 0.5661201  0.2584617 ]
 [0.40778097 0.91705336 0.23269842 0.80289503 0.14516506]
 [0.35870182 0.78633498 0.41069322 0.90580429 0.48550738]]

Randomized Array2:
[[ 1.94796512 -0.4351993   0.85872544 -0.61407851 -0.46670109]
 [-0.24439679  0.96538974 -0.15477649 -2.47459828  1.05948555]
 [-0.09748698  0.95564939  0.10705128 -1.14735714 -0.1997135 ]
 [ 0.58502339  1.45312383 

In [13]:
#array indexing

random_array = np.random.randn(5,5)

print(random_array)

print('\nFirst row of the array:\n')
print(random_array[0])

print('\nFirst column of the array:\n')
print(random_array[:, 0])

print('\nFirst and last rows of the array:\n')
print(random_array[[0, 4], :])

print('\nSpecified elements of array:\n')
print(random_array[[0, 1, 4], [1, 2, 3]])

print('\nDiagonal of random array:\n')
print(np.diagonal(random_array))

[[ 0.6733486  -1.33206964 -0.6259248   0.85520855  0.68015605]
 [ 1.06402289  2.12570672 -0.66845859 -1.22054423  0.59566371]
 [-0.82983149 -1.10963659  0.72973012  1.41846562  0.57178663]
 [-1.08419375  0.01700259 -0.21712392  0.33136416  1.23218517]
 [-2.12138718 -0.32071895  0.59985209  0.75312626 -0.36532561]]

First row of the array:

[ 0.6733486  -1.33206964 -0.6259248   0.85520855  0.68015605]

First column of the array:

[ 0.6733486   1.06402289 -0.82983149 -1.08419375 -2.12138718]

First and last rows of the array:

[[ 0.6733486  -1.33206964 -0.6259248   0.85520855  0.68015605]
 [-2.12138718 -0.32071895  0.59985209  0.75312626 -0.36532561]]

Specified elements of diagonal:

[-1.33206964 -0.66845859  0.75312626]

Diagonal of random array:

[ 0.6733486   2.12570672  0.72973012  0.33136416 -0.36532561]


In [0]:
random_array2 = np.random.randn(5, 5)
print(random_array2)

random_bool_array = random_array2 >= 0
print("\nBool Array:")
print(random_bool_array)

[[-0.85882014 -1.44876895  0.31240715 -0.15561012  0.80581399]
 [-0.53131211  1.51428098  0.1272938   0.49908999 -0.1333367 ]
 [-1.23239668 -0.20822807 -0.32938801  1.70440833 -1.23026427]
 [ 1.46936634 -0.65560674  1.62011084  0.08997262 -0.47591055]
 [ 0.47607628 -0.62859604 -0.66384045 -0.53558791 -0.93513312]]

Bool Array:
[[False False  True False  True]
 [False  True  True  True False]
 [False False False  True False]
 [ True False  True  True False]
 [ True False False False False]]


In [0]:
#Elementwise array operations

arr1 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
arr2 = np.array([[4, 5, 6], [4, 5, 6], [4, 5, 6]])

print("Array addition(elementwise):")
#print(arr1 + arr2)
print(np.add(arr1, arr2))

print("\nArray subtraction(elementwise):")
#print(arr2 - arr1)
print(np.subtract(arr2, arr1))

print("\nArray multiplication(elementwise):")
#print(arr2 * arr1)
print(np.multiply(arr2, arr1))

print("\nArray division(elementwise):")
#print(arr2 / arr1)
print(np.divide(arr2, arr1))

Array addition(elementwise):
[[5 7 9]
 [5 7 9]
 [5 7 9]]

Array subtraction(elementwise):
[[3 3 3]
 [3 3 3]
 [3 3 3]]

Array multiplication(elementwise):
[[ 4 10 18]
 [ 4 10 18]
 [ 4 10 18]]

Array division(elementwise):
[[4.  2.5 2. ]
 [4.  2.5 2. ]
 [4.  2.5 2. ]]


In [0]:
#sum function

print(arr1, '\n')
print(np.sum(arr1), '\n')

print(np.sum(arr1, axis = 0), '\n')
print(np.sum(arr1, axis = 0, keepdims=True), '\n')

print(np.sum(arr1, axis=1), '\n')
print(np.sum(arr1, axis=1, keepdims=True), '\n')

#transpose

not_symmetric_array = np.random.randn(5,7)
print(not_symmetric_array.T.shape)


[[1 2 3]
 [1 2 3]
 [1 2 3]] 

18 

[3 6 9] 

[[3 6 9]] 

[6 6 6] 

[[6]
 [6]
 [6]] 

(7, 5)


In [0]:
import time
#vectorization

rand_arr1 = np.random.randn(1000,)
rand_arr2 = np.random.randn(1000,)

#Classic Dot Product
temp = 0
tik = time.process_time()
for i in range(1000):
  temp = temp + float(rand_arr1[i]*rand_arr2[i])
tok = time.process_time()
print("Without vectorization (in milliseconds): "+str((tok-tik)*1000))

tik = time.time()
temp = np.dot(rand_arr1, rand_arr2)
tok = time.time()
print("\nWith vectorization (in milliseconds): " +str((tok-tik)*1000))

print("\n------------------------------------------------------------\n")

#Outer Product
tic = time.process_time()
outer = np.zeros((len(rand_arr1),len(rand_arr2)))
for i in range(len(rand_arr1)):
    for j in range(len(rand_arr2)):
        outer[i,j] = rand_arr1[i]*rand_arr2[j]
toc = time.process_time()
print("\nOuter Product without vectorization (in milliseconds): " + str((toc-tic)*1000))

tic = time.process_time()
outer = np.zeros((len(rand_arr1),len(rand_arr2)))
outer = np.outer(rand_arr1, rand_arr2)
toc = time.process_time()
print("\nOuter Product: with vectorization (in milliseconds): " + str((toc-tic)*1000))

print("\n------------------------------------------------------------\n")

#Elementwise Multiplication
mul = np.zeros((1000,))
tik = time.process_time()
for i in range(1000):
    mul[i] = rand_arr1[i]*rand_arr2[i]
tok = time.process_time()
print("\nElementwise multiplication without vectorization(in milliseconds): "+str((tok-tik)*1000))


tik = time.process_time()
mul = np.multiply(rand_arr1, rand_arr2)
tok = time.process_time()
print("\nElementwise multiplication with vectorization(in milliseconds): "+str((tok-tik)*1000))

Without vectorization (in milliseconds): 1.0973399999998357

With vectorization (in milliseconds): 0.13303756713867188

------------------------------------------------------------


Outer Product without vectorization (in milliseconds): 510.397143

Outer Product: with vectorization (in milliseconds): 4.532780999999986

------------------------------------------------------------


Elementwise multiplication without vectorization(in milliseconds): 0.5132750000003128

Elementwise multiplication with vectorization(in milliseconds): 0.05262200000011319
